config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users
  resources :items, only: :order do
    post 'order', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :item_order
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: :order
  
  def index
    @items = Item.all
  end

  def order
    ItemOrder.create(item_id: params[:id])
    redirect_to root_path
  end

  private

  def find_item
    Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class='nav'>
  <% if user_signed_in? %>
    <%= link_to current_user.nickname, "#", class: "user-nickname" %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
  <% else %>
    <%= link_to 'ログイン', user_session_path, class: "login" %>
    <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
  <% end %>
</div>

<div class="content">
  <% @items.each do |item| %> 
    <p>商品名：<%= item.name %></p>
    <p>値段：<%= item.price %>円</p>
    <% if item.item_order != nil %>
      <div class='sold-out'>
        <b>Sold Out!!</b>
      </div>
    <% else %>
      <% if user_signed_in? %>
        <%= link_to '購入する', order_item_path(item.id), method: :post %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>